apiVersion: v1
kind: Service
metadata:
  name: argocd-kube-sv  # kubectl get svc

spec:
  ports:
    - port: 80          # docker run -d -p 80:80

  selector:
    run: argocd-kube    # deployment.yaml 파일에 있는 라벨과 일치해야 한다!

  type: LoadBalancer
